FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY admin /usr/share/nginx/html/admin
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY assets /usr/share/nginx/html/assets
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
